### PR TITLE
Be more optimistic about the Rails dependency

### PR DESCRIPTION
**Pull request by aried3r**
Rails 5.2 stable is out :)

http://weblog.rubyonrails.org/2018/4/9/Rails-5-2-0-final/

### CODE REVIEW

**Comment by fringd** [comment]
Hey I'm happy to bump the version, but I'd prefer to bump it to < 5.3. Have you verified zipline works with 5.2?

My worry is that they'll deprecate the janky streaming API that zipline uses.

**Comment by aried3r** [comment]
Personally I'd rather have a more optimistic version locking so we don't have to do this every minor version. Also, historically speaking, the last time a `x.3.z` version or Rails has been released was [in 2009](https://rubygems.org/gems/rails/versions), with the last update in 2013. Not that this is any hard evidence.  
Maybe more so is the fact that `master` is now targeting Rails 6.0, not 5.3.

I can still change it if you want :)

**Comment by aried3r** [comment]
Ah, I forgot to answer re: testing with 5.2: Yes, at least the tests in this repo run with 5.2 if that is any indication. Sadly I can't test with our own app yet, since this and a few other gems have locks `< 5.2`. I can try with 5.2.rc2.

Speaking of testing, would it be possible to test this gem on Travis?

**Comment by fringd** [comment]
we don't have any real integration tests yet, so it's just been verified manually by me for each new rails version. I'll get around to verifying it soon.

**Comment by fringd** [comment]
i would LOVE to have a real integration tests out a real rails controller somehow, but I think it's kind of hard, especially verifying that streaming is working with s3 and whatnot.

**Comment by aried3r** [comment]
I can verify it works with 5.2.0.rc2.

**Comment by fringd** [comment]
Cool thanks!

**Comment by aried3r** [comment]
Sure! I'll just come back and do `< 6` in a year or so ;)

**Comment by aried3r** [comment]
Done!

**Comment by aried3r** [comment]
On further inspection, this gem doesn't have a hard dependency on Rails at all. Couldn't we just remove it?

**Comment by fringd** [comment]
I beg to differ. It's designed to work with ActionController::Streaming,
and depends on setting headers and response_body. These APIs might change
in a future version of rails.

**Pull request merged**
