### PR TITLE
Doc reflecting ActiveStorage example

### PR DESCRIPTION
**Pull request by mapreal19**

### CODE REVIEW

**Comment by mapreal19** [comment]
SInce Paperclip is now deprecated I thought is better how to do it with ActiveStorage. Thoughts?

**Comment by fringd** [comment]
So you have to pass in ".avatar.blob" with ActiveStorage? I didn't realize this. I've changed it so that you can just pass in avatar. Does this address your concern? And can you verify it works for you with the master for me? I haven't got an app with ActiveStorage set up.

**Comment by mapreal19** [comment]
@fringd I've checked and `file` in my case is a `ActiveStorage::Attached::One`

maybe having this condition may work?

`elsif defined?(ActiveStorage::Blob) && file.respond_to?(:blob) && file.blob.is_a?(ActiveStorage::Blob)`

Also for getting the url I think we should use the helper from Rails: https://edgeguides.rubyonrails.org/active_storage_overview.html#linking-to-files

**Comment by mapreal19** [comment]
see #45

**Pull request closed without merging**
